### PR TITLE
A sketch of how per-spider pipelines could work

### PR DESCRIPTION
**Pull request by jallum**
This would allow a pipeline config that looks like this:
```
  pipelines: %{
    Some.Spider.ForASpecificSite => [
      Crawly.Pipelines.Validate,
      Crawly.Pipelines.JSONEncoder,
      Crawly.Pipelines.WriteToFile
    ],
    default: [
      Crawly.Pipelines.Validate,
      Crawly.Pipelines.DuplicatesFilter,
      Crawly.Pipelines.JSONEncoder,
      Crawly.Pipelines.WriteToFile
    ]
  }
```

...while allowing a fallback to the existing one-size-fits all pipeline list. The "default:" entry is optional, and would be used if no spider-specific entry is found in the map (otherwise, [] as now.)

### CODE REVIEW

**Comment by oltarasenko** [comment]
**[I am just thinking out loudly]**

I just wonder what if we define these on spider level instead? E.g. from one side, we will have more simple config, and spider would kind of guess what should be done....

however, from the other side. Do we want to do write to file inside every spider? Should spiders know where to send the data, etc?

**Comment by Ziinc** [comment]
A spider could be scraping multiple data types from a page.

I suppose that there could be source-specific data cleaning steps, but no reason why it can't be implemented as a conditional step in a pipeline.

As mentioned in #20, a possible method is struct-based filtering or conditional pipeline logic (or a combinationoof both).

@jallum 's example could also be implemented as a Case pipeline, matching elixir's `case` behaviour. Less new things to learn too.

**Comment by Ziinc** [comment]
From my point of view, a set of pipelines should suit the scraped item, since the cleaning methods would be specific to that data structure.

The spider doesn't have to know what happens afterwards, it's only concerned with the extraction. The post-processing is an entirely separate phase.

An analogy is photography. The image capture process may be different for each photo, but the the post-processing would depend on what type of image you intend to produce.

**Comment by Ziinc** [comment]
> As mentioned in #20, a possible method is struct-based filtering or conditional pipeline logic (or a combinationoof both).
> 
> @jallum 's example could also be implemented as a Case pipeline, matching elixir's `case` behaviour. 

Something like this (with #22 resolved) :
```elixir
pipelines: [
    ...,
    {Crawly.Pipelines.Logic, func: case do
        {_item, %{spider_name: s} = state} when s == MySpiderName -> [ MySpiderSpecificPipeline ]
        _ -> [ MyDefaultPipeline ]
    end},
    Crawly.Pipelines.WriteToFile
]
```
where the `Crawly.Pipelines.Logic` receives a function as a parameter that dynamically decides the subsequent pipelines based on the item-state tuple it receives.

This makes it more flexible, as by using the using the item-state tuple:
1. we can check on where the item came from (using state.spider_name) 
2. we can perform checks on the item (thereby resolving #20)
3. non-breaking change (would just need #22 implemented, which is backwards compatible)
4. simple to ship (would simply be a recursive call to `Crawly.Utils.pipe`, would only need 1 new pipeline module to be maintained)
5. generalized enough to accept any function that returns a pipeline declaration list, making it more flexible for other use/edge cases.
6. can possibly be refined further for use with middlewares

**Comment by oltarasenko** [comment]
Now again, why would we need a separate pipelines set for a spider after all?

E.g. a pipeline is a generic way of working with multiple spiders. E.g. if I want to generate uuids based on some fields, or drop items without prices everywhere, I would use pipeline. So the spider code does not know about it.

I think the main concern is related to a question:  Do we need per spider configuration of the pipelines?

**Comment by jallum** [comment]
It's a fair question. In my use case, I have a good number of spiders that produce a single type of item. I'm anticipating that I'll soon have need for another group of spiders that produce something different. I'll need to process those items differently, and route them to a different place. So, I guess I could restate the question as, "Would it be useful to be able to process different _types of items_ with different pipelines?"

Asked that way, I think that tweaking my suggestion above to key off the type of struct produced (instead of the spider that produced it) would maybe make more sense.

**Comment by Ziinc** [comment]
> "Would it be useful to be able to process different types of items with different pipelines?"
This is also the issue i am facing (as already mentioned in #20. Right now I'm experimenting with the key denoting the data type, and the nested value as the scraped item and filtering
```elixir
item = %{
    weather: %{ weather_data: "bla" }
    article: %{ article_data: "bla" }
}

# in custom pipeline
case item do
    %{weather: weather} -> ... # clean weather data
    %{article: article -> ... # clean article data
    %{comments: comments-> ... # clean comments data
end
```
This approach results in:
- fat pipeline module
- non-reusable logic
- single pipeline module

and my config becomes just a single declaration, which seems counter-intuitive to what a pipeline is for:
```elixir
pipelines: [MyFatPipeline]
```

**Comment by Ziinc** [comment]
@jallum Refer to this comment on item-based pipeline definitions

**Comment by oltarasenko** [comment]
@Ziinc Can I also know more about your case? E.g. I want to keep the code simple... (ideally). Maybe I will be able to advise something if I will play with your problem a bit. (Maybe lets proceed in a ticket, as the PR should stay clean of non code related conversation)

**Comment by Ziinc** [comment]
Closing for now. api discussion to continue in #20

**Pull request closed without merging**
