### PR TITLE
Behaviour for nested values for csvencoder

### PR DESCRIPTION
**Pull request by Ziinc**
branched from #29 , added failing test.

This assumes the behaviour of nested values are flattened to json.

For consideration.

### CODE REVIEW

**Comment by Ziinc** [comment]
@oltarasenko in your opinion, is this a worthwhile improvement? If not, this pr can be closed

**Comment by oltarasenko** [comment]
@Ziinc isn't it related to #29? I thought looking on it after merging the 29th..

**Comment by Ziinc** [comment]
Ah ok

**Comment by Ziinc** [comment]
noncritical

**Pull request closed without merging**
