### PR TITLE
Migrate the static documentation to ex_doc

### PR DESCRIPTION
**Pull request by oltarasenko**

### CODE REVIEW

**Comment by Ziinc** [comment]
Will we be using https://oltarasenko.github.io/crawly/ or the one on hexdocs https://hexdocs.pm/crawly/api-reference.html ? if we're using the hexdocs endpoint, then i'll remove files for the github pages

**Comment by Ziinc** [comment]
the site at hexdocs has a higher google ranking

**Comment by oltarasenko** [comment]
I would move to hexdocs eventually. The problem here is that current github pages has several links from articles I have written before. So I would want to keep it for some time (or to make a link from github pages to hexdocs (I kind of like what I see on hexdocs already))

**Comment by Ziinc** [comment]
Looks good to me, I've made more edits and merged some sections of the guide. I've also grouped the modules together based on reader relevance.

I think the docs can be made more concise, but I'll do that on a separate PR.

**Comment by Ziinc** [comment]
travis checks failed for a non-related test. Good to merge

**Comment by oltarasenko** [comment]
I think one of the tests has a race condition. I will merge this now.

**Pull request merged**
